// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8TrERA_f9xjsNS2xg1EaI95YU5v51PYs',
    appId: '1:1014154059769:web:842ab5c11743b20d206728',
    messagingSenderId: '1014154059769',
    projectId: 'sol-mvp-4f7c1',
    authDomain: 'sol-mvp-4f7c1.firebaseapp.com',
    storageBucket: 'sol-mvp-4f7c1.firebasestorage.app',
    measurementId: 'G-D07SKZ8DPZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiJzf9MFqqudgDV8uN6G0X9KbU96ukjdc',
    appId: '1:1014154059769:android:248d2958402eafee206728',
    messagingSenderId: '1014154059769',
    projectId: 'sol-mvp-4f7c1',
    storageBucket: 'sol-mvp-4f7c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhpKsVv-sofTxFHPDQ9h1xpgr7EgOHyuM',
    appId: '1:1014154059769:ios:fa1ff8be0b5c772c206728',
    messagingSenderId: '1014154059769',
    projectId: 'sol-mvp-4f7c1',
    storageBucket: 'sol-mvp-4f7c1.firebasestorage.app',
    androidClientId: '1014154059769-rs3krvs2d8o3qqt1t3q32vl9r9v7h4ts.apps.googleusercontent.com',
    iosClientId: '1014154059769-hvbbpbkmt0mcd98b895dp2f4o3s4ben2.apps.googleusercontent.com',
    iosBundleId: 'com.solmvp.companionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhpKsVv-sofTxFHPDQ9h1xpgr7EgOHyuM',
    appId: '1:1014154059769:ios:fa1ff8be0b5c772c206728',
    messagingSenderId: '1014154059769',
    projectId: 'sol-mvp-4f7c1',
    storageBucket: 'sol-mvp-4f7c1.firebasestorage.app',
    androidClientId: '1014154059769-rs3krvs2d8o3qqt1t3q32vl9r9v7h4ts.apps.googleusercontent.com',
    iosClientId: '1014154059769-hvbbpbkmt0mcd98b895dp2f4o3s4ben2.apps.googleusercontent.com',
    iosBundleId: 'com.solmvp.companionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8TrERA_f9xjsNS2xg1EaI95YU5v51PYs',
    appId: '1:1014154059769:web:678bb7430ff3db7a206728',
    messagingSenderId: '1014154059769',
    projectId: 'sol-mvp-4f7c1',
    authDomain: 'sol-mvp-4f7c1.firebaseapp.com',
    storageBucket: 'sol-mvp-4f7c1.firebasestorage.app',
    measurementId: 'G-SKKZSY7S3P',
  );
}
