// =============================================================================
// main.dart — Sol App Entry Point with Firebase + Auth Gate
// =============================================================================
//
// AUTH GATE PATTERN:
//   Instead of hardcoding which screen to show, we use Firebase's
//   authStateChanges() stream. This stream emits:
//     - User object → show ChatScreen
//     - null         → show LoginScreen
//
//   This means:
//   - First launch: null → LoginScreen
//   - After login: User → ChatScreen (persists across restarts)
//   - After logout: null → LoginScreen again
//
//   Firebase handles session persistence automatically.
//   The user never has to log in again unless they explicitly sign out.
// =============================================================================

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';

import 'screens/login_screen.dart';
import 'screens/chat_screen.dart';
import 'firebase_options.dart'; // Auto-generated by FlutterFire CLI

void main() async {
  // Required before any async work in main()
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase — must happen before any Firebase calls
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // Lock to portrait
  await SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
  ]);

  // Full dark system UI
  SystemChrome.setSystemUIOverlayStyle(const SystemUiOverlayStyle(
    statusBarColor: Colors.transparent,
    statusBarIconBrightness: Brightness.light,
    systemNavigationBarColor: Color(0xFF0A0E1A),
    systemNavigationBarIconBrightness: Brightness.light,
  ));

  runApp(const SolApp());
}

class SolApp extends StatelessWidget {
  const SolApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Sol',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        brightness: Brightness.dark,
        scaffoldBackgroundColor: const Color(0xFF0A0E1A),
        colorScheme: ColorScheme.fromSeed(
          seedColor: const Color(0xFFF5A623), // Amber from logo
          brightness: Brightness.dark,
          background: const Color(0xFF0A0E1A),
          surface: const Color(0xFF141B2D),
        ),
        splashFactory: NoSplash.splashFactory,
        highlightColor: Colors.transparent,
        useMaterial3: true,
      ),
      // Auth gate: streams Firebase auth state to decide which screen to show
      home: const _AuthGate(),
    );
  }
}

// =============================================================================
// Auth Gate — listens to Firebase and routes to correct screen
// =============================================================================

class _AuthGate extends StatelessWidget {
  const _AuthGate();

  @override
  Widget build(BuildContext context) {
    return StreamBuilder<User?>(
      stream: FirebaseAuth.instance.authStateChanges(),
      builder: (context, snapshot) {
        // Still waiting for Firebase to check stored session
        if (snapshot.connectionState == ConnectionState.waiting) {
          return const _SplashScreen();
        }

        // User is logged in → go to chat
        if (snapshot.hasData && snapshot.data != null) {
          return const ChatScreen();
        }

        // No user → show login
        return const LoginScreen();
      },
    );
  }
}

// =============================================================================
// Splash Screen — shown for ~1 second while Firebase checks auth state
// =============================================================================

class _SplashScreen extends StatelessWidget {
  const _SplashScreen();

  static const Color _navy = Color(0xFF0A0E1A);
  static const Color _amber = Color(0xFFF5A623);
  static const Color _stone = Color(0xFFE8DCC8);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: _navy,
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            // Logo
            Image.asset(
              'assets/images/sol_logo.png',
              width: 80,
              height: 80,
              fit: BoxFit.contain,
              errorBuilder: (_, __, ___) => Container(
                width: 80,
                height: 80,
                decoration: BoxDecoration(
                  shape: BoxShape.circle,
                  color: _amber.withOpacity(0.15),
                ),
                child: Center(
                  child: Text(
                    'S',
                    style: TextStyle(
                      color: _stone.withOpacity(0.6),
                      fontSize: 32,
                      fontWeight: FontWeight.w200,
                    ),
                  ),
                ),
              ),
            ),
            const SizedBox(height: 24),
            SizedBox(
              width: 20,
              height: 20,
              child: CircularProgressIndicator(
                strokeWidth: 1,
                valueColor: AlwaysStoppedAnimation<Color>(
                  _amber.withOpacity(0.5),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
