// =============================================================================
// main.dart — Sol App Entry Point with Firebase + Auth Gate
// =============================================================================
//
// AUTH + ONBOARDING GATE PATTERN:
//   Instead of hardcoding which screen to show, we use Firebase's
//   authStateChanges() stream and then resolve whether the signed-in user
//   still needs the first-run encounter flow.
//
//   This means:
//   - First launch: null → LoginScreen
//   - After first login: User → OnboardingScreen → ChatScreen
//   - Later launches: User → ChatScreen
//   - After logout: null → LoginScreen again
//
//   Firebase handles session persistence automatically.
//   The user never has to log in again unless they explicitly sign out.
// =============================================================================

import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

import 'screens/chat_screen.dart';
import 'screens/login_screen.dart';
import 'screens/onboarding_screen.dart';
import 'services/api_service.dart';
import 'services/onboarding_service.dart';
import 'services/session_bootstrap_service.dart';
import 'firebase_options.dart'; // Auto-generated by FlutterFire CLI

void main() async {
  // Required before any async work in main()
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase — must happen before any Firebase calls
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // Lock to portrait
  await SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
  ]);

  // Full dark system UI
  SystemChrome.setSystemUIOverlayStyle(const SystemUiOverlayStyle(
    statusBarColor: Colors.transparent,
    statusBarIconBrightness: Brightness.light,
    systemNavigationBarColor: Color(0xFF0A0E1A),
    systemNavigationBarIconBrightness: Brightness.light,
  ));

  runApp(const SolApp());
}

class SolApp extends StatelessWidget {
  const SolApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Sol',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        brightness: Brightness.dark,
        scaffoldBackgroundColor: const Color(0xFF0A0E1A),
        colorScheme: ColorScheme.fromSeed(
          seedColor: const Color(0xFFF5A623), // Amber from logo
          brightness: Brightness.dark,
          background: const Color(0xFF0A0E1A),
          surface: const Color(0xFF141B2D),
        ),
        splashFactory: NoSplash.splashFactory,
        highlightColor: Colors.transparent,
        useMaterial3: true,
      ),
      // Auth gate: streams Firebase auth state to decide which screen to show
      home: const _AuthGate(),
    );
  }
}

// =============================================================================
// Auth Gate — listens to Firebase and routes to correct screen
// =============================================================================

class _AuthGate extends StatefulWidget {
  const _AuthGate();

  @override
  State<_AuthGate> createState() => _AuthGateState();
}

class _AuthGateState extends State<_AuthGate> {
  Future<_GateDecision>? _decisionFuture;
  String? _decisionUid;

  Future<_GateDecision> _resolve(User user) async {
    final complete = await OnboardingService.isComplete(user.uid);
    return _GateDecision(
      uid: user.uid,
      needsOnboarding: !complete,
    );
  }

  Future<void> _finishOnboarding(SessionStartResponse session) async {
    final uid = FirebaseAuth.instance.currentUser?.uid;
    if (uid == null) {
      return;
    }
    await OnboardingService.markComplete(uid);
    if (!mounted) {
      return;
    }
    setState(() {
      SessionBootstrapService.stash(session);
      _decisionFuture = Future.value(
        _GateDecision(uid: uid, needsOnboarding: false),
      );
      _decisionUid = uid;
    });
  }

  @override
  Widget build(BuildContext context) {
    return StreamBuilder<User?>(
      stream: FirebaseAuth.instance.authStateChanges(),
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return const _SplashScreen();
        }

        final user = snapshot.data;
        if (user != null) {
          if (_decisionUid != user.uid) {
            _decisionUid = user.uid;
            SessionBootstrapService.clear();
            _decisionFuture = _resolve(user);
          }

          return FutureBuilder<_GateDecision>(
            future: _decisionFuture,
            builder: (context, decisionSnapshot) {
              if (decisionSnapshot.connectionState != ConnectionState.done) {
                return const _SplashScreen();
              }

              final decision = decisionSnapshot.data;
              if (decision == null) {
                return const _SplashScreen();
              }

              if (decision.needsOnboarding) {
                return OnboardingScreen(onComplete: _finishOnboarding);
              }

              return ChatScreen(
                key: ValueKey('chat-${decision.uid}'),
              );
            },
          );
        }

        _decisionFuture = null;
        _decisionUid = null;
        SessionBootstrapService.clear();
        return const LoginScreen();
      },
    );
  }
}

class _GateDecision {
  final String uid;
  final bool needsOnboarding;

  const _GateDecision({
    required this.uid,
    required this.needsOnboarding,
  });
}

// =============================================================================
// Splash Screen — shown for ~1 second while Firebase checks auth state
// =============================================================================

class _SplashScreen extends StatelessWidget {
  const _SplashScreen();

  static const Color _navy = Color(0xFF0A0E1A);
  static const Color _amber = Color(0xFFF5A623);
  static const Color _stone = Color(0xFFE8DCC8);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: _navy,
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            // Logo
            Image.asset(
              'assets/images/sol_logo.png',
              width: 80,
              height: 80,
              fit: BoxFit.contain,
              errorBuilder: (_, __, ___) => Container(
                width: 80,
                height: 80,
                decoration: BoxDecoration(
                  shape: BoxShape.circle,
                  color: _amber.withOpacity(0.15),
                ),
                child: Center(
                  child: Text(
                    'S',
                    style: TextStyle(
                      color: _stone.withOpacity(0.6),
                      fontSize: 32,
                      fontWeight: FontWeight.w200,
                    ),
                  ),
                ),
              ),
            ),
            const SizedBox(height: 24),
            SizedBox(
              width: 20,
              height: 20,
              child: CircularProgressIndicator(
                strokeWidth: 1,
                valueColor: AlwaysStoppedAnimation<Color>(
                  _amber.withOpacity(0.5),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
