-- =============================================================================
-- schema.sql — SQLite Database Schema for Companion AI
-- =============================================================================
--
-- PURPOSE:
--   Defines the structure of the SQLite database that stores STRUCTURED data.
--   Think of this as the "hard facts" layer — things that should ALWAYS be
--   remembered about a user, not just retrieved by similarity.
--
-- TWO MEMORY SYSTEMS (understand this distinction):
--   1. SQLite (this file) — Structured facts: name, birthday, job, preferences.
--      Always loaded. Always in context. Never forgotten.
--
--   2. ChromaDB (vector DB) — Episodic memories: "she mentioned her dog died",
--      "he's stressed about exams". Retrieved by semantic similarity to the
--      current conversation. Fuzzy, emotional, contextual.
--
-- HOW IT'S USED:
--   - backend/db/ holds companion.db (the actual SQLite file, gitignored)
--   - store.py runs this schema at startup if tables don't exist yet
--   - The context_builder.py queries these tables to inject facts into prompts
--
-- TO APPLY MANUALLY:
--   sqlite3 backend/db/companion.db < backend/db/schema.sql
-- =============================================================================


-- ---------------------------------------------------------------------------
-- users — one row per user (for MVP, likely just one row)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
    id              TEXT PRIMARY KEY,           -- UUID, generated at onboarding
    created_at      DATETIME DEFAULT CURRENT_TIMESTAMP,
    last_seen       DATETIME DEFAULT CURRENT_TIMESTAMP,

    -- Onboarding data (collected in the first session)
    name            TEXT,                       -- "Call me Aryan" → stored here
    preferred_name  TEXT,                       -- nickname if different
    age             INTEGER,
    location        TEXT,                       -- city/country, not GPS
    timezone        TEXT,                       -- e.g. "Asia/Kolkata" for timing

    -- Relationship metadata
    character_id    TEXT DEFAULT 'nova',        -- which AI companion they chose
    relationship_label TEXT DEFAULT 'friend',   -- how user defines the relationship

    -- Session tracking (for retention analytics)
    total_sessions  INTEGER DEFAULT 0,
    total_messages  INTEGER DEFAULT 0
);


-- ---------------------------------------------------------------------------
-- user_facts — structured key-value facts extracted from conversations
-- ---------------------------------------------------------------------------
-- These are things Nova should ALWAYS know. Unlike ChromaDB memories (which
-- are retrieved by relevance), these are injected into EVERY prompt.
-- Keep this table lean — only facts that define who the user IS.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS user_facts (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id         TEXT NOT NULL REFERENCES users(id),

    category        TEXT NOT NULL,              -- 'personal', 'work', 'relationships',
                                                --   'preferences', 'goals', 'struggles'
    key             TEXT NOT NULL,              -- 'job', 'favorite_music', 'sister_name'
    value           TEXT NOT NULL,              -- 'software engineer', 'lo-fi hip hop', 'Priya'
    confidence      REAL DEFAULT 1.0,           -- 0.0–1.0, how sure we are
    source          TEXT DEFAULT 'extracted',   -- 'onboarding' | 'extracted' | 'user_stated'

    created_at      DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at      DATETIME DEFAULT CURRENT_TIMESTAMP,

    -- Prevent duplicate keys per user (UPSERT target)
    UNIQUE(user_id, key)
);


-- ---------------------------------------------------------------------------
-- conversations — tracks each conversation session
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS conversations (
    id              TEXT PRIMARY KEY,           -- UUID
    user_id         TEXT NOT NULL REFERENCES users(id),
    character_id    TEXT NOT NULL DEFAULT 'nova',

    started_at      DATETIME DEFAULT CURRENT_TIMESTAMP,
    ended_at        DATETIME,                   -- NULL if session still open
    message_count   INTEGER DEFAULT 0,

    -- A brief summary of this conversation (generated by summarizer.py after session ends)
    -- Used to compress old sessions into the long-term context without burning tokens
    summary         TEXT
);


-- ---------------------------------------------------------------------------
-- messages — every single message exchanged
-- ---------------------------------------------------------------------------
-- This is the raw conversation history. Recent messages are pulled directly
-- into the prompt. Older messages are summarized into ChromaDB.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS messages (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    conversation_id TEXT NOT NULL REFERENCES conversations(id),
    user_id         TEXT NOT NULL REFERENCES users(id),

    role            TEXT NOT NULL CHECK(role IN ('user', 'assistant')),
    content         TEXT NOT NULL,

    created_at      DATETIME DEFAULT CURRENT_TIMESTAMP,

    -- Was this message used in memory extraction already?
    memory_extracted INTEGER DEFAULT 0           -- 0 = pending, 1 = done
);


-- ---------------------------------------------------------------------------
-- memories — index of what's been stored in ChromaDB
-- ---------------------------------------------------------------------------
-- ChromaDB handles the vector embeddings. This table is the structured index:
-- it tracks what memories exist, when they were created, and their metadata.
-- On startup, we can cross-reference to ensure ChromaDB and SQLite are in sync.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS memories (
    id              TEXT PRIMARY KEY,           -- UUID, matches ChromaDB document ID
    user_id         TEXT NOT NULL REFERENCES users(id),

    -- The actual memory text (e.g. "User's dog is named Mango and he loves her")
    content         TEXT NOT NULL,

    -- Emotion/importance tagging for retrieval ranking
    emotion_tag     TEXT,                       -- 'grief', 'excitement', 'anxiety', null
    importance      REAL DEFAULT 0.5,           -- 0.0 (trivial) to 1.0 (critical)

    -- Source tracking
    source_message_ids TEXT,                    -- JSON array of message IDs this came from
    conversation_id TEXT REFERENCES conversations(id),

    created_at      DATETIME DEFAULT CURRENT_TIMESTAMP,

    -- Soft delete: mark memories as irrelevant without losing the record
    archived        INTEGER DEFAULT 0
);


-- ---------------------------------------------------------------------------
-- Indexes — speed up the queries that fire on every message
-- ---------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_messages_conversation
    ON messages(conversation_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_messages_user_unextracted
    ON messages(user_id, memory_extracted);

CREATE INDEX IF NOT EXISTS idx_user_facts_user
    ON user_facts(user_id, category);

CREATE INDEX IF NOT EXISTS idx_memories_user
    ON memories(user_id, importance DESC, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_conversations_user
    ON conversations(user_id, started_at DESC);